#! /usr/bin/env python3
import json
from src import precommit_main as main

with open('hookconfig.json', 'r') as configfile:
    CONFIG = json.load(configfile)

if __name__ == "__main__":
    main(CONFIG)