#! /usr/bin/env python3
'''
Git hook that will:
    1. Check to make sure we Master
    2. Make sure there are commits to push
    3. if on Master, run tests
        if tests fail, abort push.
'''
import argparse
import json
import subprocess
import sys
from src.prepush import prepush_main as main

with open('hookconfig.json', 'r') as configfile:
    CONFIG = json.load(configfile)

if __name__ == "__main__":
    main(CONFIG['pre-push'])